language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nehm33/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nehm33/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-031838601299"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
